apiVersion: v2
name: confluent-kafka
description: A Helm chart for Confluent Kafka 
type: application

version: 0.1.0
appVersion: "1.16.0"


dependencies:
- name: confluent-for-kubernetes
  version: "0.435.23"
  repository: "https://packages.confluent.io/helm"