apiVersion: platform.confluent.io/v1beta1
kind: Connect
metadata:
  name: kafka-connect
spec:
  replicas: 1
  image:
    application: confluentinc/cp-server-connect:7.0.1
    init: confluentinc/confluent-init-container:2.2.0-1
  build:
    type: onDemand                                              
    onDemand:
      plugins:
        locationType: confluentHub                             
        confluentHub:                                          
          - name: kafka-connect-http                                              
            owner: confluentinc
            version: 1.5.3
          - name: kafka-connect-http                                              
            owner: castorm
            version: 0.8.6
      storageLimit: 1G