apiVersion: platform.confluent.io/v1beta1
kind: Connector
metadata:
  name: kafka-http-connector
spec:
  taskMax: 10
  class: "io.confluent.connect.http.HttpSourceConnector"
  configs: 
    topics: "topic-test-1"
    tasks.max: "1"
    connector.class: "io.confluent.connect.http.HttpSinkConnector"
    http.api.url: "http://localhost:8080/api/messages"
    value.converter: "org.apache.kafka.connect.storage.StringConverter"
    confluent.topic.bootstrap.servers: "kafka:9092"
    confluent.topic.replication.factor: "1"
    reporter.bootstrap.servers: "kafka:9092"
    reporter.result.topic.name: "success-responses"
    reporter.result.topic.replication.factor: "1"
    reporter.error.topic.name: "error-responses"
    reporter.error.topic.replication.factor: "1"
  restartPolicy:
    type: OnFailure
    maxRetry: 10
